import type { Metadata } from "next";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { History } from "./_components/History";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <Show when="signed-out">
            <div className="w-full min-h-screen flex flex-col justify-center items-center p-4 gap-4">
              <p className="font-semibold text-xl">Quiz app</p>
              <div className="flex gap-3">
                <SignInButton />
                <SignUpButton mode="modal">
                  <button className="bg-blue-700 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </div>
            </div>
          </Show>

          <Show when="signed-in">
            <div className="bg-gray-200 min-h-fit">
              <header className="flex justify-between px-10 py-5 bg-white z-50">
                <Link href="/">
                  <p className="text-2xl font-semibold">Quiz App</p>
                </Link>
                <UserButton />
              </header>

              <div>
                <SidebarProvider>
                  <History />

                  <SidebarTrigger />
                  <main className="min-h-screen w-full flex items-start justify-center">
                    {children}
                  </main>
                </SidebarProvider>
              </div>
            </div>
          </Show>
        </ClerkProvider>
      </body>
    </html>
  );
}
